import { execFile } from 'node:child_process';
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const workspaceRoot = path.resolve(__dirname, '..', '..');
const iconsDirectory = path.join(workspaceRoot, 'node_modules', 'lucide-static', 'icons');
const outputDirectory = path.join(
    workspaceRoot,
    'packages',
    'lwc',
    'app',
    'component',
    'slds',
    'lucideIcon'
);
const outputFile = path.join(outputDirectory, 'constants.ts');
const prettierBinary = path.join(workspaceRoot, 'node_modules', '.bin', 'prettier');
const execFileAsync = promisify(execFile);

const iconTagPattern = /<(path|circle|ellipse|line|polygon|polyline|rect)\s+([^>]+?)\s*\/>/g;
const attributePattern = /([a-z0-9:-]+)="([^"]*)"/g;

function parseAttributes(attributesSource) {
    const attributes = {};

    for (const match of attributesSource.matchAll(attributePattern)) {
        const [, attributeName, attributeValue] = match;
        attributes[attributeName] = attributeValue;
    }

    return attributes;
}

function parseIconNodes(svgSource) {
    const nodes = [];

    for (const match of svgSource.matchAll(iconTagPattern)) {
        const [, tag, rawAttributes] = match;
        nodes.push({
            tag,
            attributes: parseAttributes(rawAttributes),
        });
    }

    return nodes;
}

function formatNode(node, index) {
    const entries = Object.entries(node.attributes).map(([attributeName, attributeValue]) => {
        return `${attributeName}: ${JSON.stringify(attributeValue)}`;
    });
    const parts = [
        `key: ${JSON.stringify(`${node.tag}-${index}`)}`,
        `tag: ${JSON.stringify(node.tag)}`,
    ];

    if (entries.length) {
        parts.push(...entries);
    }

    return `        { ${parts.join(', ')} }`;
}

function formatIconEntry(iconName, nodes) {
    const nodeLines = nodes.length
        ? nodes.map((node, index) => formatNode(node, index)).join(',\n')
        : '';

    return `    ${JSON.stringify(iconName)}: [\n${nodeLines}\n    ]`;
}

async function buildLucideConstants() {
    const iconFiles = (await readdir(iconsDirectory))
        .filter(fileName => fileName.endsWith('.svg'))
        .sort((left, right) => left.localeCompare(right));

    const iconEntries = [];

    for (const iconFile of iconFiles) {
        const iconName = iconFile.replace(/\.svg$/u, '');
        const svgSource = await readFile(path.join(iconsDirectory, iconFile), 'utf8');
        const nodes = parseIconNodes(svgSource);
        iconEntries.push(formatIconEntry(iconName, nodes));
    }

    return `// Generated by tools/scripts/generate_lucide_icons.mjs from lucide-static.
// Do not edit this file by hand.

export const LUCIDE_ICONS = {
${iconEntries.join(',\n')}
};

export const LUCIDE_ICON_NAMES = Object.keys(LUCIDE_ICONS);
`;
}

async function main() {
    await mkdir(outputDirectory, { recursive: true });
    const constantsSource = await buildLucideConstants();
    await writeFile(outputFile, constantsSource, 'utf8');
    await execFileAsync(prettierBinary, ['--write', outputFile], {
        cwd: workspaceRoot,
    });
    // eslint-disable-next-line no-console
    console.log(`Generated Lucide constants at ${path.relative(workspaceRoot, outputFile)}`);
}

await main();
