/**
 * Walks ALL *.SKILL.md files under assets/skills/ and writes
 * assets/skills/manifest.json so fs.ts can discover them dynamically
 * without any hardcoded path list.
 *
 * Usage: node tools/scripts/generate_manifest_skill.js
 */

const fs = require('fs');
const path = require('path');

const PROJECT_ROOT = path.resolve(__dirname, '../..');
const ALL_SKILLS_ROOT = path.join(PROJECT_ROOT, 'assets/skills');
const MANIFEST_FILE = path.join(PROJECT_ROOT, 'assets/skills/manifest.json');

/** Recursively collect all *.SKILL.md paths relative to `baseDir`. */
function collectSkillPaths(dir, baseDir) {
    const results = [];
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
        const fullPath = path.join(dir, entry.name);
        if (entry.isDirectory()) {
            results.push(...collectSkillPaths(fullPath, baseDir));
        } else if (entry.name.endsWith('.SKILL.md')) {
            results.push(path.relative(baseDir, fullPath).replace(/\\/g, '/'));
        }
    }
    return results.sort();
}

function generateManifest() {
    const skillPaths = collectSkillPaths(ALL_SKILLS_ROOT, ALL_SKILLS_ROOT);
    const manifest = {
        _comment: 'Auto-generated by tools/scripts/generate_manifest_skill.js — do not edit. Run: npm run generate:skills-manifest',
        skills: skillPaths,
    };
    fs.writeFileSync(MANIFEST_FILE, JSON.stringify(manifest, null, 2) + '\n', 'utf8');
    console.log('Generated', MANIFEST_FILE, 'with', skillPaths.length, 'skill paths.');
}

generateManifest();
