export const theme = {
    "borderStyles": {},
    "borderWidths": {},
    "colors": {
        "accent-primary-base": "#DFF976",
        "accent-secondary-base": "#BDB1F6",
        "accent-secondary-subtle": "#D4CCFF",
        "accent-secondary-high": "#E5E0FF",
        "accent-trial-base": "#BDB1F6",
        "accent-trial-subtle": "#D4CCFF",
        "neutral-bg-low": "#000000",
        "neutral-bg-base": "#0D0D0D",
        "neutral-bg-subtle": "#1A1A1A",
        "neutral-bg-medium": "#333333",
        "neutral-bg-high": "#525252",
        "neutral-bg-contrast": "#FFFFFF",
        "neutral-bg-focus": "#FFFFFF1A",
        "neutral-bg-focus_contrast": "#0000001A",
        "neutral-bg-base_transparent": "#0D0D0D00",
        "neutral-fg-low": "#ADADAD",
        "neutral-fg-base": "#CCCCCC",
        "neutral-fg-subtle": "#E6E6E6",
        "neutral-fg-medium": "#F2F2F2",
        "neutral-fg-high": "#FFFFFF",
        "informative-warning-base": "#F7E06E",
        "informative-alert-base": "#F6B98E",
        "informative-error-base": "#F5A8A8",
        "informative-error-subtle": "#FAD6D6",
        "informative-success-base": "#A3EC98",
        "informative-info-base": "#A8BFFA",
        "support-git-modified": "#F7E06E",
        "support-git-untracked": "#A3EC98",
        "support-git-deleted": "#F5A8A8",
        "support-git-renamed": "#CCCCCC",
        "support-git-conflict": "#F6B98E",
        "support-system-selection": "#9D8BF933",
        "support-system-terminal": "#000000",
        "support-system-scrollbar": "#F2F2F233"
    },
    "fontSizes": {
        "12": "1.2rem",
        "13": "1.3rem",
        "14": "1.4rem",
        "16": "1.6rem",
        "24": "2.4rem",
        "32": "3.2rem",
        "48": "4.8rem",
        "64": "6.4rem",
        "code": "$fontSizes$13",
        "xs": "$fontSizes$12",
        "base": "$fontSizes$13",
        "sm": "$fontSizes$16",
        "md": "$fontSizes$24",
        "lg": "$fontSizes$32",
        "xl": "$fontSizes$48",
        "xxl": "$fontSizes$64"
    },
    "fontWeights": {
        "regular": "400",
        "medium": "500",
        "semibold": "600"
    },
    "fonts": {
        "base": "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen-Sans, Ubuntu, Cantarell, 'Helvetica Neue', sans-serif",
        "display": "Everett, Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen-Sans, Ubuntu, Cantarell, 'Helvetica Neue', sans-serif",
        "mono": "Fira Code, SFMono-Regular, Consolas, 'Liberation Mono', Menlo, Courier, monospace"
    },
    "letterSpacings": {
        "0": "-0.03em",
        "1": "-0.02em",
        "2": "-0.01em",
        "3": "0em",
        "4": "0.05em",
        "5": "0.01em",
        "code": "$letterSpacings$3",
        "xs": "$letterSpacings$4",
        "base": "$letterSpacings$3",
        "sm": "$letterSpacings$2",
        "md": "$letterSpacings$2",
        "lg": "$letterSpacings$1",
        "xl": "$letterSpacings$1",
        "xxl": "$letterSpacings$0"
    },
    "lineHeights": {
        "20": "1.25em",
        "30": "1.35em",
        "code": "$lineHeights$30",
        "xs": "$lineHeights$20",
        "base": "$lineHeights$20",
        "sm": "$lineHeights$30",
        "md": "$lineHeights$30",
        "lg": "$lineHeights$30",
        "xl": "$lineHeights$30",
        "xxl": "$lineHeights$30"
    },
    "radii": {
        "1": "2px",
        "2": "4px",
        "3": "8px"
    },
    "shadows": {
        "popup": "0px 2px 7px rgba(0, 0, 0, 0.15), 0px -2px 7px rgba(0, 0, 0, 0.15), 0px 5px 17px rgba(0, 0, 0, 0.3)"
    },
    "sizes": {
        "0": "0px",
        "1": "4px",
        "2": "8px",
        "3": "12px",
        "4": "16px",
        "5": "20px",
        "6": "24px",
        "7": "28px",
        "8": "32px",
        "9": "36px",
        "10": "40px",
        "11": "44px",
        "12": "48px",
        "13": "52px",
        "14": "56px",
        "15": "60px",
        "16": "64px",
        "17": "68px",
        "18": "72px",
        "19": "76px",
        "20": "80px",
        "21": "84px",
        "22": "88px",
        "23": "92px",
        "24": "96px",
        "25": "100px"
    },
    "space": {
        "0": "0px",
        "1": "4px",
        "2": "8px",
        "3": "12px",
        "4": "16px",
        "5": "20px",
        "6": "24px",
        "7": "28px",
        "8": "32px",
        "9": "36px",
        "10": "40px",
        "11": "44px",
        "12": "48px",
        "13": "52px",
        "14": "56px",
        "15": "60px",
        "16": "64px",
        "17": "68px",
        "18": "72px",
        "19": "76px",
        "20": "80px",
        "21": "84px",
        "22": "88px",
        "23": "92px",
        "24": "96px",
        "25": "100px"
    },
    "transitions": {
        "fast": "125ms ease-in",
        "slow": "300ms cubic-bezier(0.2, 1, 0.2, 1)",
        "transform": "transform $slow",
        "background": "background $fast",
        "opacity": "opacity $fast"
    },
    "zIndices": {
        "base": "1",
        "menuOverlay": "2",
        "menu": "3",
        "overlay": "4",
        "dialog": "10",
        "commandPalette": "11",
        "top": "20"
    }
}