export const TYPE = {
    ALL: 'All',
    APEX_TRIGGER: 'Apex Trigger',
    APEX_CLASS: 'Apex Class',
    AURA: 'Aura',
    LINK: 'Link',
    DEV_LINK: 'Dev Link',
    LWC: 'LWC',
    OBJECT: 'Object',
    PROFILE: 'Profile',
    PERMISSION_SET: 'Permission Set',
    USER: 'User',
    FLOW: 'Flow',
    AGENTFORCE: 'Agentforce',
    CUSTOM: 'Custom',
};
