export const Constants = {
    ERROR_MESSAGE_DEFAULT: 'An error occurred with this message.',
    TOAST_CLIPBOARD_LABEL: 'Message exported to your clipboard',
    TOOL_RUNNING_TITLE: 'Calling function',
    TOOL_FINISHED_TITLE: 'Called function',
    TOOL_RESPONSE_SHOW: 'Show Tool Response',
    TOOL_RESPONSE_HIDE: 'Hide Tool Response',
    TOOL_PARAMS_SHOW: 'Show Tool Parameters',
    TOOL_PARAMS_HIDE: 'Hide Tool Parameters',
    TOOL_COMMAND_LABEL: 'COMMAND',
    TOOL_RESULT_LABEL: 'RESULT',
    TOOL_ICON_PREVIEW: 'utility:preview',
    TOOL_ICON_HIDE: 'utility:hide',
    SENDER_USER: 'You',
    SENDER_ASSISTANT: 'Assistant',
    SCROLL_THRESHOLD: 5,
    WELCOME_MESSAGE: {
        id: 'WELCOME_MESSAGE_ID',
        role: 'assistant',
        parts: [
            {
                type: 'text',
                text: 'Hello, I am the Workbench Assistant, I can help you interact with Salesforce and Salesforce tools.',
            },
        ],
    },
    CONTENT_TYPE: {
        TEXT: 'text',
        REASONING: 'reasoning',
        SUMMARY_TEXT: 'summary_text',
        INPUT_TEXT: 'input_text',
        OUTPUT_TEXT: 'output_text',
        INPUT_IMAGE: 'input_image',
        IMAGE: 'image',
        OUTPUT_IMAGE: 'output_image',
        INPUT_FILE: 'input_file',
    },
    MESSAGE_TYPE: {
        TOOL: 'tool',
        TOOL_CALL: 'tool-call',
        TOOL_RESULT: 'tool-result',
        REASONING: 'reasoning',
        FUNCTION_CALL: 'function_call',
        FUNCTION_CALL_PENDING: 'function_call_pending',
        FUNCTION_CALL_RESULT: 'function_call_result',
        FUNCTION_CALL_OUTPUT: 'function_call_output',
        TOOL_GROUP: 'tool_group',
    },
    STREAM_CHUNK_TYPE: {
        START: 'start',
        START_STEP: 'start-step',
        FINISH_END: 'finish-step',
        FINISH: 'finish',
        TEXT_START: 'text-start',
        TEXT_DELTA: 'text-delta',
        TEXT_END: 'text-end',
        REASONING_START: 'reasoning-start',
        REASONING_DELTA: 'reasoning-delta',
        REASONING_END: 'reasoning-end',
        TOOL_INPUT_START: 'tool-input-start',
        TOOL_INPUT_DELTA: 'tool-input-delta',
        TOOL_INPUT_END: 'tool-input-end',
        TOOL_CALL_STREAMING_START: 'tool-call-streaming-start',
        TOOL_CALL_DELTA: 'tool-call-delta',
        TOOL_CALL_END: 'tool-call-end',
        TOOL_CALL: 'tool-call',
        TOOL_RESULT: 'tool-result',
        TOOL_ERROR: 'tool-error',
        RAW: 'raw',
    },
    REASONING_LABEL_THINKING: 'Thinking',
    REASONING_LABEL_THOUGHT_FOR: 'Thought for',
    REASONING_LABEL_THOUGHT_BRIEFLY: 'Thought briefly',
};

export const SKILLS_ROOT = '/workspace/skills';

export const SKILLS_INSTRUCTIONS = `AGENT SKILLS (optional):
The following <available_skills> list specialized workflows. Use them when they might help the user's request — not only on exact keyword matches.
If a skill's description fits the task or could improve consistency, read that skill's instructions first using read_file with the path from <location>, then follow the SKILL.md body.
Paths inside a skill (scripts/, references/, assets/) are relative to the skill directory (the folder containing SKILL.md); prefer absolute paths in tool calls.`;
