/**
 * Reads *.SKILL.md files from applications/einstein/agent/tools/skills/
 * and generates defaultToolSkillsContent.generated.js so default agent skills
 * load their content from those files. Run this when you change any .SKILL.md file.
 *
 * Usage: node scripts/generate_default_skill_content.js
 */

const fs = require('fs');
const path = require('path');

const PROJECT_ROOT = path.resolve(__dirname, '..');
const SKILLS_DIR = path.join(
    PROJECT_ROOT,
    'src/client/lwc/applications/einstein/agent/tools/skills'
);
const OUTPUT_FILE = path.join(
    PROJECT_ROOT,
    'src/client/lwc/modules/shared/defaultAgentSkills/defaultToolSkillsContent.generated.js'
);

function main() {
    if (!fs.existsSync(SKILLS_DIR)) {
        console.error('Skills directory not found:', SKILLS_DIR);
        process.exit(1);
    }

    const files = fs.readdirSync(SKILLS_DIR).filter((f) => f.endsWith('.SKILL.md'));
    const contentByKey = {};

    for (const file of files) {
        const id = file.replace(/\.SKILL\.md$/, '');
        const filePath = path.join(SKILLS_DIR, file);
        const raw = fs.readFileSync(filePath, 'utf8');
        contentByKey[id] = raw;
    }

    const entries = Object.entries(contentByKey).map(([id, content]) => {
        const escaped = content
            .replace(/\\/g, '\\\\')
            .replace(/`/g, '\\`')
            .replace(/\$/g, '\\$');
        return '    ' + JSON.stringify(id) + ': `' + escaped + '`,';
    });

    const lines = [
        '// Generated by scripts/generate_default_skill_content.js — do not edit.',
        '// Edit the .SKILL.md files under applications/einstein/agent/tools/skills/ and run:',
        '//   node scripts/generate_default_skill_content.js',
        '',
        'export const SKILL_CONTENT = {',
        ...entries,
        '};',
        ''
    ];

    fs.writeFileSync(OUTPUT_FILE, lines.join('\n'), 'utf8');
    console.log('Generated', OUTPUT_FILE, 'with', Object.keys(contentByKey).length, 'skills.');
}

main();
