import accessAnalyzer_app from 'accessAnalyzer/app';
import anonymousApex_app from 'anonymousApex/app';
import api_app from 'api/app';
import code_app from 'code/app';
import dataImport_app from 'dataImport/app';
import files_app from 'files/app';
import metadata_app from 'metadata/app';
import sobjectExplorer_app from 'object/app';
import org_app from 'org/app';
import package_app from 'package/app';
import platformEvent_app from 'platformevent/app';
import recordViewer_app from 'recordviewer/app';
import soql_app from 'soql/app';

const APPLICATION_MENU_GROUPS = [
    {
        key: 'data',
        label: 'Data',
        iconName: 'utility:database',
        order: 20,
    },
    {
        key: 'code',
        label: 'Code',
        iconName: 'standard:apex',
        order: 30,
    },
    {
        key: 'explorers',
        label: 'Explorers',
        iconName: 'standard:knowledge',
        order: 40,
    },
    {
        key: 'deploy',
        label: 'Deploy',
        iconName: 'standard:maintenance_asset',
        order: 50,
    },
];

const APPLICATION_ENTRIES = [
    {
        name: 'org/app',
        module: org_app,
        isFullHeight: true,
        isDeletable: false,
        isElectronOnly: false,
        isOfflineAvailable: false,
        isMenuVisible: false,
        isTabVisible: true,
        label: 'Org. Overview',
        type: 'explorer',
        description: 'Org. Overview',
        quickActionIcon: 'standard:account',
        shortName: 'Org',
        path: 'org',
        menuGroup: 'explorers',
        menuOrder: 50,
    },
    {
        name: 'files/app',
        module: files_app,
        isFullHeight: true,
        isDeletable: true,
        isElectronOnly: false,
        isOfflineAvailable: true,
        // Files explorer is intentionally not shown in the left navigation.
        // It remains accessible via direct navigation (e.g. Settings button).
        isMenuVisible: false,
        isTabVisible: true,
        label: 'Files',
        type: 'explorer',
        description: 'Browse your virtual workspace',
        quickActionIcon: 'utility:open_folder',
        shortName: 'Files',
        path: 'files',
        menuGroup: 'explorers',
        menuOrder: 5,
    },
    {
        name: 'accessAnalyzer/app',
        module: accessAnalyzer_app,
        isFullHeight: true,
        isDeletable: true,
        isElectronOnly: false,
        isOfflineAvailable: false,
        isMenuVisible: true,
        isTabVisible: true,
        label: 'Access Analyzer',
        type: 'explorer',
        description: 'Review/Compare the access provided by the Permission sets & Profiles.',
        quickActionIcon: 'standard:portal',
        shortName: 'Access.',
        path: 'access',
        menuGroup: 'explorers',
        menuOrder: 60,
    },
    {
        name: 'code/app',
        module: code_app,
        isFullHeight: true,
        isDeletable: true,
        isElectronOnly: true,
        isOfflineAvailable: false,
        isMenuVisible: true,
        isTabVisible: true,
        label: 'Code Toolkit',
        type: 'developer',
        description:
            'Retrieve Code, Run Static code analysis, Open visualforce. A perfect toolkit to simplify your life (Electron only).',
        quickActionIcon: 'standard:apex',
        shortName: 'Code',
        path: 'code',
        menuGroup: 'code',
        menuOrder: 40,
    },
    {
        name: 'metadata/app',
        module: metadata_app,
        isFullHeight: true,
        isDeletable: true,
        isElectronOnly: false,
        isOfflineAvailable: false,
        isMenuVisible: true,
        isTabVisible: true,
        label: 'Metadata Explorer',
        type: 'explorer',
        description: 'Review & Modify all your metadata. (Beta)',
        quickActionIcon: 'standard:knowledge',
        shortName: 'Metad.',
        path: 'metadata',
        menuGroup: 'explorers',
        menuOrder: 10,
    },
    {
        name: 'object/app',
        module: sobjectExplorer_app,
        isFullHeight: true,
        isDeletable: true,
        isElectronOnly: false,
        isOfflineAvailable: false,
        isMenuVisible: true,
        isTabVisible: true,
        label: 'SObject Explorer',
        type: 'explorer',
        description: 'Explore in details all your SObjects',
        quickActionIcon: 'standard:knowledge',
        shortName: 'SObject',
        path: 'sobject',
        menuGroup: 'explorers',
        menuOrder: 20,
    },
    {
        name: 'soql/app',
        module: soql_app,
        isFullHeight: true,
        isDeletable: true,
        isElectronOnly: false,
        isOfflineAvailable: false,
        isMenuVisible: true,
        isTabVisible: true,
        label: 'SOQL Explorer',
        type: 'developer',
        description: 'Build SOQL queries with fields suggestion and export them.',
        quickActionIcon: 'standard:data_model',
        shortName: 'SOQL',
        path: 'soql',
        menuGroup: 'data',
        menuOrder: 10,
    },
    {
        name: 'dataImport/app',
        module: dataImport_app,
        isFullHeight: true,
        isDeletable: true,
        isElectronOnly: false,
        isOfflineAvailable: false,
        isMenuVisible: true,
        isTabVisible: true,
        label: 'Data Import',
        type: 'data',
        description: 'Insert/Update/Upsert records from CSV using REST or Bulk APIs.',
        quickActionIcon: 'standard:data_model',
        shortName: 'Import',
        path: 'dataimport',
        menuGroup: 'data',
        menuOrder: 20,
    },
    {
        name: 'recordviewer/app',
        module: recordViewer_app,
        isFullHeight: true,
        isDeletable: true,
        isElectronOnly: false,
        isOfflineAvailable: false,
        isMenuVisible: true,
        isTabVisible: true,
        label: 'Record Viewer',
        type: 'explorer',
        description: 'Explore in details your records',
        quickActionIcon: 'standard:knowledge',
        shortName: 'Rec. Viewer',
        path: 'recordviewer',
        menuGroup: 'explorers',
        menuOrder: 30,
    },
    {
        name: 'api/app',
        module: api_app,
        isFullHeight: true,
        isDeletable: true,
        isElectronOnly: false,
        isOfflineAvailable: false,
        isMenuVisible: true,
        isTabVisible: true,
        label: 'API Explorer',
        type: 'developer',
        description: 'Explore Salesforce API',
        quickActionIcon: 'standard:apex',
        shortName: 'API',
        path: 'api',
        menuGroup: 'code',
        menuOrder: 10,
    },
    {
        name: 'platformevent/app',
        module: platformEvent_app,
        isFullHeight: true,
        isDeletable: true,
        isElectronOnly: false,
        isOfflineAvailable: false,
        isMenuVisible: true,
        isTabVisible: true,
        label: 'Event Explorer',
        type: 'developer',
        description: 'Subscribe to platform event to visualize them.',
        quickActionIcon: 'standard:events',
        shortName: 'PLEV',
        path: 'platformevent',
        menuGroup: 'code',
        menuOrder: 20,
    },
    {
        name: 'anonymousApex/app',
        module: anonymousApex_app,
        isFullHeight: true,
        isDeletable: true,
        isElectronOnly: false,
        isOfflineAvailable: false,
        isMenuVisible: true,
        isTabVisible: true,
        label: 'Anonymous Apex',
        type: 'developer',
        description: 'Execute Apex Scripts',
        quickActionIcon: 'standard:apex',
        shortName: 'APEX',
        path: 'anonymousapex',
        menuGroup: 'code',
        menuOrder: 30,
    },
    {
        name: 'package/app',
        module: package_app,
        isFullHeight: true,
        isDeletable: true,
        isElectronOnly: false,
        isOfflineAvailable: false,
        isMenuVisible: true,
        isTabVisible: true,
        label: 'Deploy/Retrieve',
        type: 'data',
        description: '',
        quickActionIcon: 'standard:maintenance_asset',
        shortName: 'PACK',
        path: 'package',
        menuGroup: 'deploy',
        menuOrder: 10,
    },
];

const APPLICATION_APP_MAPPING = APPLICATION_ENTRIES.reduce((acc, entry) => {
    const { name, ...settings } = entry;
    acc[name] = settings;
    return acc;
}, {});

export { APPLICATION_APP_MAPPING, APPLICATION_MENU_GROUPS };
