export default {
    "actionOverrides": [],
  "activateable": false,
  "associateEntityType": null,
  "associateParentEntity": null,
  "childRelationships": [
    {
      "cascadeDelete": true,
      "childSObject": "FieldPermissions",
      "deprecatedAndHidden": false,
      "field": "ParentId",
      "junctionIdListNames": [],
      "junctionReferenceTo": [],
      "relationshipName": "FieldPerms",
      "restrictedDelete": false
    },
    {
      "cascadeDelete": false,
      "childSObject": "NetworkMemberGroup",
      "deprecatedAndHidden": false,
      "field": "ParentId",
      "junctionIdListNames": [],
      "junctionReferenceTo": [],
      "relationshipName": null,
      "restrictedDelete": true
    },
    {
      "cascadeDelete": true,
      "childSObject": "ObjectPermissions",
      "deprecatedAndHidden": false,
      "field": "ParentId",
      "junctionIdListNames": [],
      "junctionReferenceTo": [],
      "relationshipName": "ObjectPerms",
      "restrictedDelete": false
    },
    {
      "cascadeDelete": false,
      "childSObject": "PermissionSetAssignment",
      "deprecatedAndHidden": false,
      "field": "PermissionSetId",
      "junctionIdListNames": [],
      "junctionReferenceTo": [],
      "relationshipName": "Assignments",
      "restrictedDelete": false
    },
    {
      "cascadeDelete": true,
      "childSObject": "PermissionSetGroupComponent",
      "deprecatedAndHidden": false,
      "field": "PermissionSetId",
      "junctionIdListNames": [],
      "junctionReferenceTo": [],
      "relationshipName": "PermissionSetGroupComponents",
      "restrictedDelete": false
    },
    {
      "cascadeDelete": true,
      "childSObject": "PermissionSetTabSetting",
      "deprecatedAndHidden": false,
      "field": "ParentId",
      "junctionIdListNames": [],
      "junctionReferenceTo": [],
      "relationshipName": null,
      "restrictedDelete": false
    },
    {
      "cascadeDelete": true,
      "childSObject": "PortalDelegablePermissionSet",
      "deprecatedAndHidden": false,
      "field": "PermissionSetId",
      "junctionIdListNames": [],
      "junctionReferenceTo": [],
      "relationshipName": null,
      "restrictedDelete": false
    },
    {
      "cascadeDelete": false,
      "childSObject": "SessionPermSetActivation",
      "deprecatedAndHidden": false,
      "field": "PermissionSetId",
      "junctionIdListNames": [],
      "junctionReferenceTo": [],
      "relationshipName": "SessionActivations",
      "restrictedDelete": false
    },
    {
      "cascadeDelete": true,
      "childSObject": "SetupEntityAccess",
      "deprecatedAndHidden": false,
      "field": "ParentId",
      "junctionIdListNames": [],
      "junctionReferenceTo": [],
      "relationshipName": "SetupEntityAccessItems",
      "restrictedDelete": false
    }
  ],
  "compactLayoutable": false,
  "createable": true,
  "custom": false,
  "customSetting": false,
  "deepCloneable": false,
  "defaultImplementation": null,
  "deletable": true,
  "deprecatedAndHidden": false,
  "extendedBy": null,
  "extendsInterfaces": null,
  "feedEnabled": false,
    "hasSubtypes": false,
    "implementedBy": null,
    "implementsInterfaces": null,
    "isInterface": false,
    "isSubtype": false,
    "keyPrefix": "0PS",
    "label": "Permission Set",
    "labelPlural": "Permission Sets",
    "layoutable": false,
    "listviewable": null,
    "lookupLayoutable": null,
    "mergeable": false,
    "mruEnabled": true,
    "name": "PermissionSet",
    "namedLayoutInfos": [],
    "networkScopeFieldName": null,
    "queryable": true,
    "recordTypeInfos": [],
    "replicateable": false,
    "retrieveable": true,
    "searchLayoutable": false,
    "searchable": true,
    "sobjectDescribeOption": "FULL",
    "fields" : [
        {
            "aggregatable": false,
            "aiPredictionField": false,
            "autoNumber": false,
            "byteLength": 0,
            "calculated": false,
            "calculatedFormula": null,
            "cascadeDelete": false,
            "caseSensitive": false,
            "compoundFieldName": null,
            "controllerName": null,
            "createable": true,
            "custom": false,
            "defaultValue": null,
            "defaultValueFormula": null,
            "defaultedOnCreate": false,
            "dependentPicklist": false,
            "deprecatedAndHidden": false,
            "digits": 0,
            "displayLocationInDecimal": false,
            "encrypted": false,
            "externalId": false,
            "extraTypeInfo": null,
            "filterable": true,
            "filteredLookupInfo": null,
            "formulaTreatNullNumberAsZero": false,
            "groupable": false,
            "highScaleNumber": false,
            "htmlFormatted": false,
            "idLookup": false,
            "inlineHelpText": null,
            "label": "View AI Insight Objects",
            "length": 0,
            "mask": null,
            "maskType": null,
            "name": "PermissionsAIViewInsightObjects",
            "nameField": false,
            "namePointing": false,
            "nillable": false,
            "permissionable": false,
            "picklistValues": [],
            "polymorphicForeignKey": false,
            "precision": 0,
            "queryByDistance": false,
            "referenceTargetField": null,
            "referenceTo": [],
            "relationshipName": null,
            "relationshipOrder": null,
            "restrictedDelete": false,
            "restrictedPicklist": false,
            "scale": 0,
            "searchPrefilterable": false,
            "soapType": "xsd:boolean",
            "sortable": false,
            "type": "boolean",
            "unique": false,
            "updateable": true,
            "writeRequiresMasterRead": false
        },
        {
            "aggregatable": false,
            "aiPredictionField": false,
            "autoNumber": false,
            "byteLength": 0,
            "calculated": false,
            "calculatedFormula": null,
            "cascadeDelete": false,
            "caseSensitive": false,
            "compoundFieldName": null,
            "controllerName": null,
            "createable": true,
            "custom": false,
            "defaultValue": null,
            "defaultValueFormula": null,
            "defaultedOnCreate": false,
            "dependentPicklist": false,
            "deprecatedAndHidden": false,
            "digits": 0,
            "displayLocationInDecimal": false,
            "encrypted": false,
            "externalId": false,
            "extraTypeInfo": null,
            "filterable": true,
            "filteredLookupInfo": null,
            "formulaTreatNullNumberAsZero": false,
            "groupable": false,
            "highScaleNumber": false,
            "htmlFormatted": false,
            "idLookup": false,
            "inlineHelpText": null,
            "label": "Activate Contracts",
            "length": 0,
            "mask": null,
            "maskType": null,
            "name": "PermissionsActivateContract",
            "nameField": false,
            "namePointing": false,
            "nillable": false,
            "permissionable": false,
            "picklistValues": [],
            "polymorphicForeignKey": false,
            "precision": 0,
            "queryByDistance": false,
            "referenceTargetField": null,
            "referenceTo": [],
            "relationshipName": null,
            "relationshipOrder": null,
            "restrictedDelete": false,
            "restrictedPicklist": false,
            "scale": 0,
            "searchPrefilterable": false,
            "soapType": "xsd:boolean",
            "sortable": false,
            "type": "boolean",
            "unique": false,
            "updateable": true,
            "writeRequiresMasterRead": false
        },
        {
            "aggregatable": false,
            "aiPredictionField": false,
            "autoNumber": false,
            "byteLength": 0,
            "calculated": false,
            "calculatedFormula": null,
            "cascadeDelete": false,
            "caseSensitive": false,
            "compoundFieldName": null,
            "controllerName": null,
            "createable": true,
            "custom": false,
            "defaultValue": null,
            "defaultValueFormula": null,
            "defaultedOnCreate": false,
            "dependentPicklist": false,
            "deprecatedAndHidden": false,
            "digits": 0,
            "displayLocationInDecimal": false,
            "encrypted": false,
            "externalId": false,
            "extraTypeInfo": null,
            "filterable": true,
            "filteredLookupInfo": null,
            "formulaTreatNullNumberAsZero": false,
            "groupable": false,
            "highScaleNumber": false,
            "htmlFormatted": false,
            "idLookup": false,
            "inlineHelpText": null,
            "label": "Activate Orders",
            "length": 0,
            "mask": null,
            "maskType": null,
            "name": "PermissionsActivateOrder",
            "nameField": false,
            "namePointing": false,
            "nillable": false,
            "permissionable": false,
            "picklistValues": [],
            "polymorphicForeignKey": false,
            "precision": 0,
            "queryByDistance": false,
            "referenceTargetField": null,
            "referenceTo": [],
            "relationshipName": null,
            "relationshipOrder": null,
            "restrictedDelete": false,
            "restrictedPicklist": false,
            "scale": 0,
            "searchPrefilterable": false,
            "soapType": "xsd:boolean",
            "sortable": false,
            "type": "boolean",
            "unique": false,
            "updateable": true,
            "writeRequiresMasterRead": false
        }
    ]
}